generator:
  class: pmPropelGenerator
  param:
    model_class:           CaracteristicaProducto
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              CaracteristicaProducto
    plural:                CaracteristicaProductos
    route_prefix:          caracteristica_producto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
      exportation: ~
