generator:
  class: pmPropelGenerator
  param:
    model_class:           SituacionImpositiva
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              SituacionImpositiva
    plural:                SituacionImpositivas
    route_prefix:          situacion_impositiva
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Situación Impositiva

      fields:
        es_activo:
          label: Activo

      list:
        title: Listado de Situaciones Impositivas
        display: [nombre, es_activo]
        max_per_page: 10

        object_actions:
          _edit:
          activar:
            action: activar
            label: Activar
            show_when: puedoActivar
          desactivar:
            action: desactivar
            label: Desactivar
            show_when: puedoDesactivar

        batch_actions: {}

      filter:  ~
      form:    ~
      edit:
        title: Editar Situación Impositiva :: %%nombre%%

        actions:
          _list:
          _save:

      new:
        title: Agregar Situación Impositiva

