  medio_pago:
    _attributes:
       phpName: MedioPago
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  venta:
    _attributes:
      phpName: Venta
    id: ~
    fecha:
      type: date
      required: true
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: true
      onDelete: restrict
    medio_pago_id:
      type: integer
      foreignClass: MedioPago
      foreignReference: id
      required: true
      onDelete: restrict
    es_activo:
      type: boolean
      required: true
      default: true

  producto_venta:
    _attributes:
      phpName: VentaProducto
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: cascade
    venta_id:
      type: integer
      foreignClass: Venta
      foreignReference: id
      required: true
      onDelete: cascade
    precio_unitario:
      type: float
      required: true
    cantidad:
      type: integer
      required: true
    es_activo:
     type: boolean
     required: true
     default: true

  #falta idCliente ,idEmpleado

