generator:
  class: pmPropelGenerator
  param:
    model_class:           StockProductoSucursal
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              StockProductoSucursal
    plural:                StockProductoSucursals
    route_prefix:          stock_producto_sucursal
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Producto

      fields:  ~
      list:
        title: Listado de Stock
        display: [producto, sucursal, cantidad]

        object_actions:
          _edit:
          _delete:

      filter:  ~
      form:    ~
      edit:
        title: Editar Stock de Producto en Sucursal (%%producto%% - Sucursal %%sucursal%%)

        actions:
          _list:
          _save:

      new:
        title: Agregar Stock a Producto en Sucursal

