generator:
  class: sfPropelGenerator
  param:
    model_class:           StockProductoSucursal
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              StockProductoSucursal
    plural:                StockProductoSucursals
    route_prefix:          stock_producto_sucursal
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
