<?php


/**
 * Skeleton subclass for representing a row from the 'caracteristica' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May 29 23:44:12 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Caracteristica extends BaseCaracteristica {

	/**
	 * Initializes internal state of Caracteristica object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

        public function __toString()
        {
          return $this->getNombre();
        }

  public function puedenBorrarme()
  {
    $criteria = new Criteria();
    $criteria->addJoin(ProductoPeer::ID, CaracteristicaProductoPeer::PRODUCTO_ID, Criteria::INNER_JOIN);
    $criteria->addJoin(CaracteristicaProductoPeer::CARACTERISTICA_ID, CaracteristicaPeer::ID, Criteria::INNER_JOIN);
    $criteria->add(ProductoPeer::ES_ACTIVO, 1);
    $criteria->addAnd(CaracteristicaPeer::ID, $this->getId());

    return (CaracteristicaPeer::doCount($criteria) == 0);
  }

} // Caracteristica
