<?php


/**
 * Skeleton subclass for representing a row from the 'categoria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jun 10 17:44:55 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Categoria extends BaseCategoria {

  public function __toString()
  {
    return $this->getNombre();
  }

  public function puedoActivar()
  {
    return !$this->getEsActivo();
  }

  public function activar()
  {
    $this->setEsActivo(true);
    $this->save();
  }

  public function puedoDesactivar()
  {
    return !$this->puedoActivar();
  }

  public function desactivar()
  {
    $this->setEsActivo(false);
    $this->save();
  }

  public function getCantidadTiposProductoActivos()
  {
    $criteria = new Criteria();
    $criteria->add(TipoProductoPeer::ES_ACTIVO, true);

    return $this->countTipoProductos($criteria);
  }

  public function getCantidadProductosActivos()
  {
    $criteria = new Criteria();
    $criteria->add(TipoProductoPeer::ES_ACTIVO, true);

    $cantidad_productos_activos = 0;

    foreach ($this->getTipoProductos($criteria) as $tipo_producto)
    {
      $cantidad_productos_activos += $tipo_producto->getCantidadProductosActivos();
    }

    return $cantidad_productos_activos;
  }

  public function puedenDesactivarme()
  {
    return $this->getCantidadTiposProductoActivos() == 0;
  }
} // Categoria
