<?php


/**
 * Skeleton subclass for representing a row from the 'Marca' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 24 02:53:51 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Marca extends BaseMarca {

  public function __toString()
  {
    return $this->getNombre();
  }

  public function puedenBorrarme()
  {
    $criteria = new Criteria();
    $criteria->addJoin(ProductoPeer::MARCA_ID, MarcaPeer::ID, Criteria::INNER_JOIN);
    $criteria->add(ProductoPeer::ES_ACTIVO, 1);
    $criteria->addAnd(MarcaPeer::ID, $this->getId());

    return (MarcaPeer::doCount($criteria) == 0);
  }

} // Marca
