<?php


/**
 * Skeleton subclass for performing query and update operations on the 'producto_venta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jun 10 23:34:01 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductoVentaPeer extends BaseProductoVentaPeer {

	public static function doCountByVenta(Criteria $criteria, $distinct = false, PropelPDO $con = null)
  {
    if ($criteria == null)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::VENTA_ID, sfContext::getInstance()->getUser()->getVenta()->getId());

    return self::doCount($criteria, $distinct, $con);
  }

	public static function doSelectByVenta(Criteria $criteria, PropelPDO $con = null)
  {
    if ($criteria == null)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::VENTA_ID, sfContext::getInstance()->getUser()->getVenta()->getId());

    return self::doSelect($criteria, $con);
  }
} // ProductoVentaPeer
