<?php


/**
 * Skeleton subclass for representing a row from the 'situaction_impositiva' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jun 25 07:31:24 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SituacionImpositiva extends BaseSituacionImpositiva {

  public function __toString()
  {
    return $this->getNombre(); 
  }

  public function puedoActivar()
  {
    return !$this->getEsActivo();
  }

  public function activar()
  {
    $this->setEsActivo(true);
    $this->save();
  }

  public function puedoDesactivar()
  {
    return !$this->puedoActivar();
  }

  public function desactivar()
  {
    $this->setEsActivo(false);
    $this->save();
  }
} // SituacionImpositiva
