<?php


/**
 * Skeleton subclass for representing a row from the 'Sucursal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 24 02:53:52 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Sucursal extends BaseSucursal {

  public function __toString()
  {
    return $this->getNombre(); 
  }

  public function puedoActivar()
  {
    return !$this->getEsActivo();
  }

  public function activar()
  {
    $this->setEsActivo(true);
    $this->save();
  }

  public function puedoDesactivar()
  {
    return !$this->puedoActivar();
  }

  public function desactivar()
  {
    $this->setEsActivo(false);
    $this->save();
  }

  public function puedenDesactivarme()
  {
    /*$criteria_stock_producto_sucursal = new Criteria();
    $criteria_stock_producto_sucursal->add(StockProductoSucursalPeer::SUCURSAL_ID, $this->getId());*/

    $criteria_perfiles = new Criteria();
    $criteria_perfiles->add(BasesfGuardUserProfilePeer::SUCURSAL_ID, $this->getId());

    //return ((ProductoPeer::doCount($criteria_producto) == 0) && (CaracteristicaPeer::doCount($criteria_caracteristica) == 0));

    return ($this->countStockProductoSucursals() && BasesfGuardUserProfilePeer::doCount($criteria_perfiles) == 0);
  }
} // Sucursal
