<?php


/**
 * Skeleton subclass for performing query and update operations on the 'Sucursal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 24 02:53:52 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SucursalPeer extends BaseSucursalPeer {

	public static function doSelectActivos(Criteria $criteria, PropelPDO $con = null)
  {
    if ($criteria === null)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::ES_ACTIVO, true);

    return self::doSelect($criteria, $con);    
  }

	public static function doCountActivos(Criteria $criteria, $distinct = false, PropelPDO $con = null)
  {
    if ($criteria === null)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::ES_ACTIVO, true);

    return self::doCount($criteria, $distinct, $con);     
  }

} // SucursalPeer
