<?php


/**
 * Skeleton subclass for representing a row from the 'Tipo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 24 02:53:51 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tipo extends BaseTipo {

  public function __toString()
  {
    return $this->getNombre();
  }

  public function getTiposHijos()
  {
    $criteria = new Criteria();
    $criteria->addJoin(TipoPeer::TIPO_PADRE_ID, $this->getId());

    return TipoPeer::doSelect($criteria);
  }

  public function getProductosAsociados()
  {
    // Falta implementar.
    return false;
  }

  public function puedenBorrarme()
  {
    $criteria = new Criteria();
    $criteria->add(TipoProductoPeer::TIPO_ID, $this->getId());

    return (TipoProductoPeer::doCount($criteria) == 0);
  }

} // Tipo
