<?php


/**
 * Skeleton subclass for performing query and update operations on the 'tipo_producto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 24 13:50:46 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TipoProductoPeer extends BaseTipoProductoPeer {

	public static function doSelectActivos(Criteria $criteria, PropelPDO $con = null)
  {
    if ($criteria === null)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::ES_ACTIVO, true);

    return self::doSelect($criteria, $con);    
  }

	public static function doCountActivos(Criteria $criteria, $distinct = false, PropelPDO $con = null)
  {
    if ($criteria === null)
    {
      $criteria = new Criteria();
    }

    $criteria->add(self::ES_ACTIVO, true);

    return self::doCount($criteria, $distinct, $con);     
  }

  public static function doSelectChoices(Criteria $criteria, PropelPDO $con = null)
  {
    $collection = self::doSelectActivos($criteria, $con);

    $choices = array();

    foreach ($collection as $object)
    {
      $choices[$object->getId()] = $object->getNombre();
    }

    return $choices;    
  }

} // TipoProductoPeer
