<?php


/**
 * Skeleton subclass for representing a row from the 'tipo_producto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 24 13:50:46 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TipoProducto extends BaseTipoProducto {

  public function __toString()
  {
    return $this->getNombre();
  }

  public function puedenBorrarme()
  {
    $criteria_producto = new Criteria();
    $criteria_producto->add(ProductoPeer::TIPO_PRODUCTO_ID, $this->getId());

    $criteria_caracteristica = new Criteria();
    $criteria_caracteristica->add(CaracteristicaPeer::TIPO_PRODUCTO_ID, $this->getId());

    return ((ProductoPeer::doCount($criteria_producto) == 0) && (CaracteristicaPeer::doCount($criteria_caracteristica) == 0));
  }

} // TipoProducto
