<?php


/**
 * Skeleton subclass for representing a row from the 'venta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jun 10 21:12:29 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Venta extends BaseVenta {

  private $productos = array();

	/**
	 * Initializes internal state of Venta object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

  public function __toString()
  {
    return $this->getFecha();
  }

  public function agregarProducto(Producto $producto)
  {
    // FALTA IMPLEMENTAR.
    return true;
  }

} // Venta
