generator:
  class: pmPropelGenerator
  param:
    model_class:           Sucursal
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Sucursal
    plural:                Sucursals
    route_prefix:          sucursal
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Sucursal

      fields:
        es_activo:
          label: Activo

      list:
        title: Listado de Sucursales
        display: [nombre, es_activo]

        object_actions:
          _edit:
          activar:
            action: activar
            label: Activar
            show_when: puedoActivar
          desactivar:
            action: desactivar
            label: Desactivar
            show_when: puedoDesactivar

        batch_actions: {}

      filter:  ~
      form:    ~
      edit:
        title: Editar Sucursal :: %%nombre%%

      new:
        title: Agregar Sucursal

