generator:
  class: pmPropelGenerator
  param:
    model_class:           Tipo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Tipo
    plural:                Tipos
    route_prefix:          tipo
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        tipo_related_by_tipo_padre_id:
          label: Tipo (padre)
      list:
        title: Listado de Tipos de Producto
        display: [nombre, tipo_related_by_tipo_padre_id]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
