<?php $host = $_SERVER['HTTP_HOST'] ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_ADDR']; ?>

# Constantes
all:

# Rutas
  url_ventas: <?php echo $host . "/ventas.php" . "\n"; ?>
  url_administracion: <?php echo $host . "/administracion.php" . "\n"; ?>

# Grupos
  grupo_empleados: 1
  grupo_supervisores: 2
  grupo_administradores: 3

# Sin seleccionar
  cliente_sin_seleccionar: 1
  medio_pago_sin_seleccionar: 1
