propel:

# Sprint 00

  preferencia:
    _attributes:
      phpName: Preferencia
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    valor:
      type: varchar(255)
      required: true
    comentario:
      type: varchar(255)

  sf_guard_user_profile:
    _attributes:
      phpName: sfGuardUserProfile
    id: ~
    user_id:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      required: true
      onDelete: cascade
    nombre:
      type: varchar(255)
    apellido:
      type: varchar(255)
    email:
      type: varchar(255)
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: true
      onDelete: restrict

# Sprint 01

  marca:
    _attributes:
      phpName: Marca
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  categoria:
    _attributes:
      phpName: Categoria
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  tipo_producto:
    _attributes:
      phpName: TipoProducto
    id: ~
    categoria_id:
      type: integer
      foreignClass: Categoria
      foreignReference: id
      onDelete: restrict
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  caracteristica:
    _attributes:
      phpName: Caracteristica
    id: ~
    tipo_producto_id:
      type: integer
      foreignClass: TipoProducto
      foreignReference: id
      required: true
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true
  
  producto:
    _attributes:
      phpName: Producto
    id: ~
    es_activo:
      type: boolean
      required: true
      default: true
    tipo_producto_id:
      type: integer
      foreignClass: TipoProducto
      foreignReference: id
      required: false
      onDelete: restrict
    marca_id:
      type: integer
      foreignClass: Marca
      foreignReference: id
      required: true
      onDelete: restrict
    modelo:
      type: varchar(255)
      index: unique
    precio:
      type: float
      required: true
    descripcion:
      type: clob
    stock_minimo:
      type: integer
      required: true
      default: 0
    imagen:
      type: varchar(255)
  
  caracteristica_producto:
    _attributes:
      phpName: CaracteristicaProducto
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: cascade
    caracteristica_id:
      type: integer
      foreignClass: Caracteristica
      foreignReference: id
      required: true
      onDelete: cascade
    es_activo:
      type: boolean
      required: true
      default: true

  stock_producto_sucursal:
    _attributes:
      phpName: StockProductoSucursal
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: restrict
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: true      
    cantidad:
      type: integer
      required: true
    _uniques:
      producto_sucursal_unique_index: [producto_id, sucursal_id]
  
  sucursal:
    _attributes:
      phpName: Sucursal
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

# Sprint 02

  medio_pago:
    _attributes:
       phpName: MedioPago
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  venta:
    _attributes:
      phpName: Venta
    id: ~
    created_at: ~
    created_by:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      required: true
      onDelete: restrict
    updated_at: ~
    updated_by:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      onDelete: restrict
    cliente_id:
      type: integer
      foreignClass: Cliente
      foreignReference: id
      required: true
      onDelete: restrict
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: false
      onDelete: restrict
    medio_pago_id:
      type: integer
      foreignClass: MedioPago
      foreignReference: id
      required: true
      onDelete: restrict
    es_finalizado:
      type: boolean
      required: true
      default: false
    es_activo:
      type: boolean
      required: true
      default: true

  producto_venta:
    _attributes:
      phpName: ProductoVenta
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: restrict
    venta_id:
      type: integer
      foreignClass: Venta
      foreignReference: id
      required: true
      onDelete: cascade
    precio_unitario:
      type: float
      required: true
    cantidad:
      type: integer
      required: true
    es_activo:
     type: boolean
     required: true
     default: true

  #falta idCliente ,idEmpleado

# Sprint 03

# Del cliente se guarda todos los datos necesarios para realizar una venta: nombre, apellido, direccion, dni o cuit.
# En el DER no estaba el CUIT asi que lo puse como opcional.

  tipo_documento:
    _attributes:
      phpName: TipoDocumento
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
  
  cliente:
    _attributes:
      phpName: Cliente
    id: ~
    tipo_documento_id:
      type: integer
      foreignClass: TipoDocumento
      foreignReference: id
      required: true
    nro_documento: 
      type: integer
      required: true
      index: unique
    apellido:
      type: varchar(255)
      required: true
    nombre:
      type: varchar(255)
      required: true
    telefono:
      type: varchar(255)
      required: true
    direccion:
      type: varchar(255)
      required: true
    cuit:
      type: integer
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

