propel:

# Sprint 00

  preferencia:
    _attributes:
      phpName: Preferencia
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    valor:
      type: varchar(255)
      required: true
    comentario:
      type: varchar(255)

  sf_guard_user_profile:
    _attributes:
      phpName: sfGuardUserProfile
    id: ~
    user_id:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      required: true
      onDelete: cascade
    nombre:
      type: varchar(255)
    apellido:
      type: varchar(255)
    email:
      type: varchar(255)
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: true
      onDelete: restrict

# Sprint 01

  marca:
    _attributes:
      phpName: Marca
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  categoria:
    _attributes:
      phpName: Categoria
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  tipo_producto:
    _attributes:
      phpName: TipoProducto
    id: ~
    categoria_id:
      type: integer
      foreignClass: Categoria
      foreignReference: id
      onDelete: restrict
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  caracteristica:
    _attributes:
      phpName: Caracteristica
    id: ~
    tipo_producto_id:
      type: integer
      foreignClass: TipoProducto
      foreignReference: id
      required: true
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true
  
  producto:
    _attributes:
      phpName: Producto
    id: ~
    es_activo:
      type: boolean
      default: true
    tipo_producto_id:
      type: integer
      foreignClass: TipoProducto
      foreignReference: id
      required: true
      onDelete: restrict
    marca_id:
      type: integer
      foreignClass: Marca
      foreignReference: id
      required: true
      onDelete: restrict
    modelo:
      type: varchar(255)
      required: true
    precio:
      type: float
      required: true
    descripcion:
      type: clob
    stock_minimo:
      type: integer
      required: true
      default: 0
    imagen:
      type: varchar(255)
    _uniques:
      marca_modelo_unique_index: [marca_id, modelo]
      
  
  caracteristica_producto:
    _attributes:
      phpName: CaracteristicaProducto
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: cascade
    caracteristica_id:
      type: integer
      foreignClass: Caracteristica
      foreignReference: id
      required: true
      onDelete: cascade
    es_activo:
      type: boolean
      required: true
      default: true

  stock_producto_sucursal:
    _attributes:
      phpName: StockProductoSucursal
    id: ~
    created_at: ~
    created_by:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      required: true
      onDelete: restrict
    updated_at: ~
    updated_by:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      onDelete: restrict
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: restrict
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: true      
    cantidad:
      type: integer
      required: true
    _uniques:
      producto_sucursal_unique_index: [producto_id, sucursal_id]
  
  sucursal:
    _attributes:
      phpName: Sucursal
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    domicilio:
      type: varchar(255)
    telefono:
      type: varchar(255)
    es_activo:
      type: boolean
      required: true
      default: true

# Sprint 02

  medio_pago:
    _attributes:
       phpName: MedioPago
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  venta:
    _attributes:
      phpName: Venta
    id: ~
    created_at: ~
    created_by:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      required: true
      onDelete: restrict
    updated_at: ~
    updated_by:
      type: integer
      foreignClass: sfGuardUser
      foreignReference: id
      onDelete: restrict
    cliente_id:
      type: integer
      foreignClass: Cliente
      foreignReference: id
      required: true
      onDelete: restrict
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: false
      onDelete: restrict
    medio_pago_id:
      type: integer
      foreignClass: MedioPago
      foreignReference: id
      required: true
      onDelete: restrict
    es_finalizado:
      type: boolean
      required: true
      default: false
    es_activo:
      type: boolean
      required: true
      default: true

  producto_venta:
    _attributes:
      phpName: ProductoVenta
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: restrict
    venta_id:
      type: integer
      foreignClass: Venta
      foreignReference: id
      required: true
      onDelete: cascade
    precio_unitario:
      type: float
      required: true
    cantidad:
      type: integer
      required: true

  tipo_factura:
    _attributes:
       phpName: TipoFactura
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  situaction_impositiva:
    _attributes:
       phpName: SituacionImpositiva
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  
  factura:
    _attributes:
      phpName: Factura
    id: ~
    venta_id:
      type: integer
      foreignClass: Venta
      foreignReference: id
      required: true
      onDelete: cascade
    tipo_factura_id:
      type: integer
      foreignClass: TipoFactura
      foreignReference: id
      required: true
      onDelete: restrict
      required: true
    nro_factura:
      type: integer
    situacion_impositiva_id:
      type: integer
      foreignClass: SituacionImpositiva
      foreignReference: id
      required: true
      onDelete: restrict
      required: true
    _uniques:
      tipo_nro_factura_unique_index: [tipo_factura_id, nro_factura]

# Sprint 03

# Del cliente se guarda todos los datos necesarios para realizar una venta: nombre, apellido, direccion, dni o cuit.
# En el DER no estaba el CUIT asi que lo puse como opcional.

  tipo_documento:
    _attributes:
      phpName: TipoDocumento
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true
  
  cliente:
    _attributes:
      phpName: Cliente
    id: ~
    tipo_documento_id:
      type: integer
      foreignClass: TipoDocumento
      foreignReference: id
      required: true
    nro_documento: 
      type: integer
      required: true
      index: unique
    apellido:
      type: varchar(255)
      required: true
    nombre:
      type: varchar(255)
      required: true
    telefono:
      type: varchar(255)
    direccion:
      type: varchar(255)
    cuit:
      type: varchar(13)
    es_activo:
      type: boolean
      required: true
      default: true

