propel:

  marca:
    _attributes:
      phpName: Marca
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique

  tipo:
    _attributes:
      phpName: Tipo
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    tipo_padre_id:
      type: integer
      foreignTable: tipo
      foreignReference: id

  caracteristica:
    _attributes:
      phpName: Caracteristica
    id: ~
    tipo_id:
      type: integer
      foreignTable: tipo
      foreignReference: id
      required: true
    nombre:
      type: varchar(255)
      required: true
      index: unique
  
  producto:
    _attributes:
      phpName: Producto
    id: ~
    marca_id:
      type: integer
      foreignTable: tipo
      foreignReference: id
      required: true
    modelo:
      type: varchar(255)
      index: unique
    precio:
      type: float
      required: true
    descripcion:
      type: blob
    # ¿Qué quiso hacer Andrés acá? Producto es una tabla de referencia, no tiene sentido meter un campo stock.
    #stock: { type: integer, foreignTable: stock, foreignReference: id, required: true, primaryKey: true, onDelete: cascade }
  
  caracteristica_producto:
    _attributes:
      phpName: CaracteristicaProducto
    producto_id:
      type: integer
      foreignTable: producto
      foreignReference: id
      required: true
      primaryKey: true
      onDelete: cascade
    caracteristica_id:
      type: integer
      foreignTable: caracteristica
      foreignReference: id
      required: true
      primaryKey: true
      onDelete: cascade
  
  tipo_producto:
    _attributes:
      phpName: TipoProducto
    producto_id:
      type: integer
      foreignTable: producto
      foreignReference: id
      required: true
      primaryKey: true
      onDelete: cascade
    tipo_id:
      type: integer
      foreignTable: tipo
      foreignReference: id
      required: true
      primaryKey: true
      onDelete: cascade

  stock_producto_sucursal:
    _attributes:
      phpName: StockProductoSucursal
    id: ~
    producto_id:
      type: integer
      foreignTable: producto
      foreignReference: id
      required: true
      primaryKey: true
      onDelete: cascade
    sucursal_id:
      type: integer
      foreignTable: sucursal
      foreignReference: id
      required: true      
    cantidad:
      type: integer
      required: true
  
  sucursal:
    _attributes:
      phpName: Sucursal
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
