propel:

  marca:
    _attributes:
      phpName: Marca
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

  tipo:
    _attributes:
      phpName: Tipo
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    tipo_padre_id:
      type: integer
      foreignClass: Tipo
      foreignReference: id
    es_activo:
      type: boolean
      required: true
      default: true

  caracteristica:
    _attributes:
      phpName: Caracteristica
    id: ~
    tipo_id:
      type: integer
      foreignClass: Tipo
      foreignReference: id
      required: true
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true
  
  producto:
    _attributes:
      phpName: Producto
    id: ~
    marca_id:
      type: integer
      foreignClass: Marca
      foreignReference: id
      required: true
    modelo:
      type: varchar(255)
      index: unique
    precio:
      type: float
      required: true
    descripcion:
      type: clob
    es_activo:
      type: boolean
      required: true
      default: true
  
  caracteristica_producto:
    _attributes:
      phpName: CaracteristicaProducto
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: cascade
    caracteristica_id:
      type: integer
      foreignClass: Caracteristica
      foreignReference: id
      required: true
      onDelete: cascade
    es_activo:
      type: boolean
      required: true
      default: true
  
  tipo_producto:
    _attributes:
      phpName: TipoProducto
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      onDelete: cascade
    tipo_id:
      type: integer
      foreignClass: Tipo
      foreignReference: id
      required: true
      onDelete: cascade
    es_activo:
      type: boolean
      required: true
      default: true

  stock_producto_sucursal:
    _attributes:
      phpName: StockProductoSucursal
    id: ~
    producto_id:
      type: integer
      foreignClass: Producto
      foreignReference: id
      required: true
      primaryKey: true
      onDelete: cascade
    sucursal_id:
      type: integer
      foreignClass: Sucursal
      foreignReference: id
      required: true      
    cantidad:
      type: integer
      required: true
  
  sucursal:
    _attributes:
      phpName: Sucursal
    id: ~
    nombre:
      type: varchar(255)
      required: true
      index: unique
    es_activo:
      type: boolean
      required: true
      default: true

