generator:
  class: pmPropelGenerator
  param:
    model_class:           Categoria
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Categoria
    plural:                Categorias
    route_prefix:          categoria
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Categoría

      fields:
        cantidad_tipos_producto_activos:
          label: '# Tipos de Producto Activos'
        cantidad_productos_activos:
          label: '# Productos Activos'

      list:
        title: Listado de Categorías
        display: [nombre, cantidad_tipos_producto_activos, cantidad_productos_activos, es_activo]
        max_per_page: 10

        object_actions:
          _edit:
          activar:
            action: activar
            show_when: puedoActivar
          desactivar:
            action: desactivar
            show_when: puedoDesactivar

        batch_actions: {}

      filter:  ~
      form:
        #display: [nombre]

      edit:
        title: Editar Categoría :: %%nombre%%

        actions:
          _list:
          _save:

      new:
        title: Agregar Categoría

