generator:
  class: sfPropelGenerator
  param:
    model_class:           Categoria
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Categoria
    plural:                Categorias
    route_prefix:          categoria
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Categoría

      fields:  ~
      list:
        title: Listado de Categorías
        display: [nombre, es_activo]

        object_actions:
          _edit:
          desactivar:
            action: desactivar

        batch_actions: {}

      filter:  ~
      form:
        display: [nombre]

      edit:
        title: Editar Categoría :: %%nombre%%

        actions:
          _list:
          _save:

      new:
        title: Agregar Categoría

