generator:
  class: sfPropelGenerator
  param:
    model_class:           TipoProducto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              TipoProducto
    plural:                TipoProductos
    route_prefix:          tipo_producto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Tipo de Producto

      fields:
        categoria:
          label: Categoría
        categoria_id:
          label: Categoría

      list:
        title: Listado de Tipos de Producto
        display: [categoria, nombre, es_activo]

        object_actions:
          _edit:
          desactivar:
            action: desactivar

        batch_actions: {}

      filter:  ~
      form:
        display: [categoria_id, nombre]

      edit:
        title: Editar Tipo de Producto :: %%categoria%% - %%nombre%%

        actions:
          _list:
          _save:

      new:
        title: Agregar Tipo de Producto
