generator:
  class: sfPropelGenerator
  param:
    model_class:           ProductoVenta
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ProductoVenta
    plural:                ProductoVentas
    route_prefix:          producto_venta
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        precio_unitario_formateado:
          label: Precio unitario
        precio_total_formateado:
          label: Precio total

      list:
        title: Productos de la Venta
        display: [producto, cantidad, precio_unitario_formateado, precio_total_formateado]
        peer_method: doSelectByVenta
        peer_count_method: doCountByVenta

        actions:
          agregar_producto:
            action: agregarProducto
            label: Agregar Producto
          cancelar_venta:
            action: cancelarVenta
            label: Cancelar Venta
          cerrar_venta:
            action: cerrarVenta
            label: Cerrar Venta
  
      filter: ~
      form:
        display: [producto_id, venta_id, cantidad]

      edit:
        title: Editar Producto de la Venta :: %%producto%%

      new:
        title: Agregar Producto a la Venta :: %%producto%%
