generator:
  class: sfPropelGenerator
  param:
    model_class:           Producto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Producto
    plural:                Productos
    route_prefix:          producto
    with_propel_route:     1
    actions_base_class:    sfActions
    #css:                   false

    config:
      actions: ~
      fields:
        _new:
          label: Agregar Producto
        _delete:
          label: Eliminar
        categoria:
          label: Categoría
        categoria_id:
          label: Categoría
        caracteristica:
          label: Características
        caracteristica_id:
          label: Características
        descripcion:
          label: Descripción
        es_activo:
          label: Activo

      list:
        title: Listado de Productos
        display: [marca, modelo, _precio, es_activo]

        object_actions:
          _edit:
            credentials: Administrador
          _delete:
            credentials: Administrador
          agregar_producto_venta:
            action: agregarProductoVenta
            #condition: algo
              #functionName: usuarioTieneVenta
            #credentials: [[Empleados]]
            label: Agregar a la Venta Activa
          ver_detalles:
            action: verDetalles

      filter:  ~
      form:
        display: [categoria_id, tipo_producto_id, marca_id, caracteristica_id, modelo, precio, descripcion]

      edit:
        title: Editar Producto :: %%tipo_producto%% - %%marca%% - %%modelo%%
      new:
        title: Agregar Producto

