generator:
  class: sfPropelGenerator
  param:
    model_class:           Producto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Producto
    plural:                Productos
    route_prefix:          producto
    with_propel_route:     1
    actions_base_class:    sfActions
    #css:                   false

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Productos
        display: [marca, modelo, _precio, es_activo]

        object_actions:
          _edit:
            credentials: Administrador
          borrar_logico:
            action: borrarLogico
            credentials: Administrador
            label: Borrar     
          ver_caracteristicas:
            action: verCaracteristicas

            

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
