generator:
  class: pmPropelGenerator
  param:
    model_class:           Producto
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Producto
    plural:                Productos
    route_prefix:          producto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        imagen_thumb:
          label:
        categoria:
          label: Categoría
        categoria_id:
          label: Categoría
        tipo_producto:
          label: Tipo
        tipo_producto_id:
          label: Tipo
        caracteristica:
          label: Características
        caracteristica_id:
          label: Características
        descripcion:
          label: Descripción
        cantidad_stock_en_mi_sucursal:
          label: Stock

      list:
        title: Listado de Productos
        display: [_imagen_thumb, marca, modelo, _precio, cantidad_stock_en_mi_sucursal]
        max_per_page: 10

        object_actions:
          ver_detalles:
            action: verDetalles
            label: +info
          agregar_producto_venta:
            action: agregarProductoVenta
            label: Agregar a la Venta Activa
            show_when: puedoAgregarProductoVenta

        batch_actions: {}

        actions: {}

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~

