generator:
  class: sfPropelGenerator
  param:
    model_class:           Producto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Producto
    plural:                Productos
    route_prefix:          producto
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   bootstrap.min.css

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Productos

      filter: ~
      form:    ~
      edit:    ~
      new:     ~
