generator:
  class: sfPropelGenerator
  param:
    model_class:           Caracteristica
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Caracteristica
    plural:                Caracteristicas
    route_prefix:          caracteristica
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Característica

      fields:
        tipo_producto:
          label: Tipo
        tipo_producto_id:
          label: Tipo

      list:    
        title: Listado de Características
        display: [tipo_producto, nombre, es_activo]

        object_actions:
          _edit:
          desactivar:
            action: desactivar

        batch_actions: {}

      filter:  ~
      form:
        display: [categoria_id, tipo_producto_id, nombre]

      edit:    
        title: Editar Característica :: %%tipo_producto%% - %%nombre%%

        actions:
          _list:
          _save:

      new:
        title: Agregar Característica

