generator:
  class: sfPropelGenerator
  param:
    model_class:           Caracteristica
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Caracteristica
    plural:                Caracteristicas
    route_prefix:          caracteristica
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar
        _edit:
          label: Editar
        _delete:
          label: Eliminar
      fields: ~
      list:    
        title: Lista de Caracteristicas
        hide: [id]
      filter:  ~
      form:    ~
      edit:    
        title: Editar Caracteristica
      new:
        title: Nueva Caracteristica