generator:
  class: pmPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUser
    plural:                sfGuardUsers
    route_prefix:          sf_guard_user
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Usuarios
        display: [username, is_active]

      filter:
        #display: [username, is_active, is_super_admin]
      form:    ~
      edit:    ~
      new:     ~
