generator:
  class: pmPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUser
    plural:                sfGuardUsers
    route_prefix:          sf_guard_user
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Usuario

      fields:
        is_active:
          label: Activo

      list:
        title: Listado de Usuarios
        display: [username, sucursal, is_active]

      filter:  ~
      form:    ~
      edit:
        title: Editar Usuario :: %%username%%

      new:
        title: Agregar Usuario
