generator:
  class: pmPropelGenerator
  param:
    model_class:           Venta
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Venta
    plural:                Ventas
    route_prefix:          venta
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        created_at:
          date_format: 'd/MM/y HH:mm'
          label: Fecha
        sf_guard_user_related_by_created_by:
          label: Empleado

      list:
        title: Listado de Ventas
        display: [created_at, sf_guard_user_related_by_created_by, cliente, sucursal, medio_pago, es_finalizado, es_activo]

        batch_actions: {}

        actions: {}
        
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
