# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            4072a79e77f969f74c241fcd814776d05959b921

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # sfGuard configuration
    enabled_modules:        [default, dc_ajax, sfGuardAuth, sfGuardUser, sfGuardGroup, sfGuardPermission]
    
    secure_module:          sfGuardAuth
    secure_action:          secure
    
    sf_guard_plugin:
      routes_register:      false

    # Settings personalizadas
    i18n:                   true
    default_culture:        es_AR
    charset:                utf-8

    error_404_module:       default
    error_404_action:       error404

  .actions:
    login_module:           sfGuardAuth
    login_action:           signin

