generator:
  class: pmPropelGenerator
  param:
    model_class: Marca
    theme: basic
    non_verbose_templates: true
    with_show: false
    singular: Marca
    plural: Marcas
    route_prefix: marca
    with_propel_route: 1
    actions_base_class: sfActions

    config:
      actions:
        _new:
          label: Agregar Marca
        _edit:
          label: Editar
        _delete:
          label: Eliminar

      fields:
        cantidad_productos_activos:
          label: '# Productos'
      list:
        title: Listado de Marcas
        display: [nombre, cantidad_productos_activos, es_activo]
        max_per_page: 10

        object_actions:
          _edit:
          activar:
            action: activar
            show_when: puedoActivar
          desactivar:
            action: desactivar
            show_when: puedoDesactivar

        batch_actions: {}

      filter: ~
      form:
        #display: [nombre]

      edit:
        title: Editar Marca

        actions:
          _list:
          _save:

      new:
        title: Agregar Marca

