generator:
  class: sfPropelGenerator
  param:
    model_class:           Marca
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Marca
    plural:                Marcas
    route_prefix:          marca
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Nuevo
        _edit:
          label: Editar
        _delete:
          label: Eliminar
      fields:  ~      
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
