generator:
  class: sfPropelGenerator
  param:
    model_class:           Cliente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Cliente
    plural:                Clientes
    route_prefix:          cliente
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        tipo_documento:
          label: Tipo
        tipo_documento_id:
          label: Tipo

      list:
        title: Listado de Clientes
        display: [tipo_documento, nro_documento, apellido, nombre]
        peer_method: doSelectValidos
        peer_count_method: doCountValidos

      filter:  ~
      form:
        display: [tipo_documento_id, nro_documento, apellido, nombre, telefono, direccion, cuit]

      edit:
        title: Editar Cliente :: %%apellido%%, %%nombre%% (%%tipo_documento%% %%nro_documento%%)

      new:
        title: Agregar Cliente


