generator:
  class: pmPropelGenerator
  param:
    model_class:           Cliente
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Cliente
    plural:                Clientes
    route_prefix:          cliente
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Cliente

      fields:
        tipo_documento:
          label: Tipo
        tipo_documento_id:
          label: Tipo

      list:
        title: Listado de Clientes
        display: [tipo_documento, nro_documento, apellido, nombre, es_activo]

        object_actions:
          _edit:
          _show:
          activar:
            action: activar
            label: Activar
            show_when: puedoActivar
          desactivar:
            action: desactivar
            label: Desactivar
            show_when: puedoDesactivar

        batch_actions: {}

      show:
        title: Ver Cliente :: %%apellido%%, %%nombre%% (%%tipo_documento%% %%nro_documento%%)
        display: [tipo_documento, nro_documento, apellido, nombre, telefono, direccion, cuit]

        actions:
          _list:

      filter:  ~
      form:    ~
      edit:
        title: Editar Cliente :: %%apellido%%, %%nombre%% (%%tipo_documento%% %%nro_documento%%)

        actions:
          _list:
          _save:

      new:
        title: Agregar Cliente

