generator:
  class: pmPropelGenerator
  param:
    model_class:           Venta
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Venta
    plural:                Ventas
    route_prefix:          venta
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Ventas
        display: [cliente, medio_pago, es_finalizado, es_activo]

        object_actions:
          ver_factura:
            action: verFactura
            show_when: puedoVerFactura
          recuperar_venta:
            action: recuperarVenta
            show_when: puedoRecuperarVenta
          #reabrir_venta:
            #condition: esFinalizada
            #action: reabrirVenta

        actions:
          iniciar_venta:
            action: iniciarVenta
            show_when: noTieneVenta
            credentials: [iniciarVenta]

      filter:
        #display: [cliente_id, medio_pago_id, es_activo]

      form:    ~
      edit:    ~
      new:     ~
