generator:
  class: pmPropelGenerator
  param:
    model_class:           Venta
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              Venta
    plural:                Ventas
    route_prefix:          venta
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _save:
          label: Cerrar Venta

      fields:
        created_at:
          label: Fecha y Hora

      list:
        title: Listado de Ventas
        display: [id, created_at, cliente, medio_pago, es_finalizado, es_activo]

        object_actions:
          ver_factura:
            action: verFactura
            show_when: puedoVerFactura
          ver_productos:
            action: verProductos
            show_when: puedoVerProductos
          recuperar_venta:
            action: recuperarVenta
            show_when: puedoRecuperarVenta

        batch_actions: {}

        actions: {}

      filter:  ~
      form:    ~
      edit:
        title: Editar Venta (%%created_at%%)

      new:     ~

