generator:
  class: sfPropelGenerator
  param:
    model_class:           Venta
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Venta
    plural:                Ventas
    route_prefix:          venta
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de Ventas
        display: [medio_pago, es_finalizado, es_activo]

        object_actions:
          reabrir_venta:
            condition: esFinalizada
            action: reabrirVenta

        actions:
          iniciar_venta:
            action: iniciarVenta

      filter:
        display: [sucursal_id, medio_pago_id, es_activo]
      form:    ~
      edit:    ~
      new:     ~
