generator:
  class: pmPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 basic
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUser
    plural:                sfGuardUsers
    route_prefix:          sf_guard_user
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          label: Agregar Usuario

      fields:
        is_active:
          label: Activo

      list:
        title: Listado de Usuarios
        display: [username, grupo, sucursal, is_active]

        object_actions:
          _edit:
          activar:
            action: activar
            label: Activar
            show_when: puedoActivar
          desactivar:
            action: desactivar
            label: Desactivar
            show_when: puedoDesactivar
          ver_ventas:
            action: verVentas
            label: Ver Ventas
            show_when: puedoVerVentas            

        batch_actions: {}

      filter:  ~
      form:    ~
      edit:
        title: Editar Usuario :: %%username%%

        actions:
          _list:
          _save:

      new:
        title: Agregar Usuario

